// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegistroDoc.Infrastructure.Persistence;

#nullable disable

namespace RegistroDoc.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegistroDocDbContext))]
    [Migration("20261007025802_AddUniqueIndexDocumentoHashSha256")]
    partial class AddUniqueIndexDocumentoHashSha256
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegistroDoc.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OcorridaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OcorridaEmUtc");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnoReferencia")
                        .HasColumnType("integer");

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("IndexadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("QuantidadePaginas")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServentiaId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusIndexacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("HashSha256")
                        .IsUnique();

                    b.HasIndex("ServentiaId");

                    b.HasIndex("StatusIndexacao");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.ExecucaoIndexacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinalizadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IniciadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MensagemErro")
                        .HasColumnType("text");

                    b.Property<int>("PaginasProcessadas")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("ExecucoesIndexacao");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.PaginaDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExtraidaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("integer");

                    b.Property<string>("TextoExtraido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "NumeroPagina")
                        .IsUnique();

                    b.ToTable("PaginasDocumento");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.Serventia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoCns")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CriadaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCns")
                        .IsUnique();

                    b.ToTable("Serventias");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.Documento", b =>
                {
                    b.HasOne("RegistroDoc.Domain.Entities.Serventia", "Serventia")
                        .WithMany()
                        .HasForeignKey("ServentiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Serventia");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.ExecucaoIndexacao", b =>
                {
                    b.HasOne("RegistroDoc.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("RegistroDoc.Domain.Entities.PaginaDocumento", b =>
                {
                    b.HasOne("RegistroDoc.Domain.Entities.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });
#pragma warning restore 612, 618
        }
    }
}
